#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

if which podman >/dev/null; then
    CONMAN="$(which podman)"
    if which buildah >/dev/null; then
        BUILDCON=("$(which buildah)" bud)
    fi
elif which docker >/dev/null; then
    CONMAN="$(which docker)"
    BUILDCON=("$CONMAN" build)
fi

CONREG="dkcr.nl"
SELF="$(realpath "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}")"
DIR="$(dirname "$SELF")"
VENDOR="$(basename "$(dirname "$DIR")")"
PROJECT="$(basename "$DIR")"
IMAGE="$CONREG/$VENDOR/$PROJECT"
VOLUMES=(-w "/opt/$VENDOR/$PROJECT" "-v" "$DIR:/opt/$VENDOR/$PROJECT:rw")

if ! "$CONMAN" images | grep -q "$IMAGE"; then
    "${BUILDCON[@]}" -t $IMAGE -f Containerfile .
fi

case "${1:-}" in
    build)
        "${BUILDCON[@]}" -t $IMAGE -f Containerfile .
        ;;

    update | require | install)
        "$CONMAN" run -it --rm -v "$DIR:/app:rw" composer composer "$@"
        ;;

    test)
        shift
        "$CONMAN" run -it --rm "${VOLUMES[@]}" "$IMAGE" \
            php /opt/$VENDOR/$PROJECT/vendor/bin/phpunit --coverage-html "/opt/$VENDOR/$PROJECT/docs/coverage" /opt/$VENDOR/$PROJECT/tests $*
        ;;

    check)
        "$CONMAN" run -it --rm "${VOLUMES[@]}" "$IMAGE" \
            find src tests -name "*.php" -type f -exec php -l "{}" \;
        ;;

    bash)
        "$CONMAN" run -it --rm "${VOLUMES[@]}" "$IMAGE" bash
        ;;

    php)
        shift
        "$CONMAN" run -it --rm "${VOLUMES[@]}" "$IMAGE" php "$@"
        ;;

    coverage)
        "$CONMAN" run --name "${VENDOR}_${PROJECT}" -d --rm "${VOLUMES[@]}" -p 8080:8080 "$IMAGE" php -S 0.0.0.0:8080 coverage.php >/dev/null
        echo "Goto http://$(ip addr show eth0 | sed -n 's/^ *inet \([^/]*\).*$/\1/p'):8080"
        ;;

    ""|help|--help|-h|-?)
        echo "Usage: $0 ( login | build | update | require | test | check | bash | coverage)"
        ;;

    *)
        echo "No such subcommand: $@"
        ;;
esac
